spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_db
    username: postgres
    password: 4321
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db.migration

server:
  port: 8080

exchange-rate:
  api:
    url: https://www.alphavantage.co/query
    key: 7QFD70HHEAOVQ3TG
